#!/usr/bin/env python3
"""
monte_carlo.py — Robust Logic-Aware Monte Carlo Simulation.

Unlike simple return shuffling, this script reconstructs the P&L by applying
the system's exact money management rules (Anti-Martingale) to shuffled
trade outcomes (R-multiples).

This captures the interaction between:
1. The sequence of wins/losses (clustering).
2. The "Immune System" (halving risk on losing streaks).
3. The friction (spread/slippage) encoded in the realized R-multiples.

It answers: "If the market gave me these same setups but in a completely
different order, would my risk management save me?"

Usage:
    1. Run a backtest and save the results:
       python scripts/backtest_per_model.py --save-csv backtest_results.csv

    2. Run the Monte Carlo simulation on the results:
       python scripts/monte_carlo.py --input backtest_results.csv
"""

import argparse
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from dotenv import load_dotenv
load_dotenv()

from core.constants import RISK_PER_TRADE_PCT, XAUUSD_POINT_VALUE

BUST_THRESHOLD = 0.50  # Bust if balance drops below $0.50


def run_simulation(r_multiples: np.ndarray, num_trades: int, start_balance: float,
                   rng: np.random.Generator) -> tuple:
    """
    Run a single Monte Carlo simulation path using system logic.
    
    Logic:
      - Base Risk: 5% of current balance.
      - Anti-Martingale: Risk halves for each consecutive loss (R < 0).
      - Reset: Risk resets to 5% after a win (R >= 0).
    """
    balance = start_balance
    peak_balance = start_balance
    max_drawdown = 0.0
    consecutive_losses = 0
    max_losing_streak = 0

    # Sample with replacement from the historical R-multiples
    random_rs = rng.choice(r_multiples, size=num_trades, replace=True)

    for r in random_rs:
        # 1. Calculate Risk % based on streak
        if consecutive_losses == 0:
            risk_pct = RISK_PER_TRADE_PCT
        else:
            risk_pct = RISK_PER_TRADE_PCT / (2 ** consecutive_losses)
        
        # 2. Apply outcome
        # PnL = Risk_Amount * R_Multiple
        # Balance_New = Balance + (Balance * Risk_Pct * R)
        balance += balance * risk_pct * r

        if balance < BUST_THRESHOLD:
            return None, 1.0, 0  # Busted

        # 3. Update State
        peak_balance = max(peak_balance, balance)
        drawdown = (peak_balance - balance) / peak_balance if peak_balance > 0 else 0.0
        max_drawdown = max(max_drawdown, drawdown)

        if r < 0:
            consecutive_losses += 1
            max_losing_streak = max(max_losing_streak, consecutive_losses)
        else:
            consecutive_losses = 0

    return balance, max_drawdown, max_losing_streak


def main():
    p = argparse.ArgumentParser(
        description="Run Monte Carlo simulation on backtest results."
    )
    p.add_argument(
        "--input", required=True,
        help="Path to the backtest CSV file generated by --save-csv."
    )
    p.add_argument(
        "--sims", type=int, default=100000,
        help="Number of simulations to run (default: 100,000)."
    )
    p.add_argument(
        "--balance", type=float, default=20.0,
        help="Starting balance for simulations (default: 20.0)."
    )
    a = p.parse_args()

    if not os.path.exists(a.input):
        print(f"ERROR: Input file not found: {a.input}", file=sys.stderr)
        sys.exit(1)

    df = pd.read_csv(a.input)
    required_cols = ["pnl", "lot_size", "sl_distance"]
    if not all(c in df.columns for c in required_cols):
        print(f"ERROR: CSV must contain {required_cols}", file=sys.stderr)
        sys.exit(1)

    # ─── Extract R-Multiples ──────────────────────────────────────────────────
    # R = Realized PnL / Theoretical Risk Amount
    # Theoretical Risk = Lot * SL_Distance * Point_Value
    # This captures spread, slippage, and partial wins/losses in a normalized unit.
    
    # Filter out invalid trades (e.g. zero risk)
    df = df[df["sl_distance"] > 0].copy()
    
    theoretical_risk = df["lot_size"] * df["sl_distance"] * XAUUSD_POINT_VALUE
    # Avoid division by zero
    theoretical_risk = theoretical_risk.replace(0, np.nan).dropna()
    
    # Auto-detect if Point Value is mismatched (e.g. Cents vs Standard)
    # If the implied R-multiples are huge (e.g. > 50R for normal trades), something is wrong.
    temp_r = (df.loc[theoretical_risk.index, "pnl"] / theoretical_risk).values
    if np.mean(np.abs(temp_r)) > 20.0 and XAUUSD_POINT_VALUE == 1:
        print("WARNING: High R-multiples detected. Data looks like Standard account but running in Cents mode.")
        print("         Switching XAUUSD_POINT_VALUE to 100 for accurate simulation.")
        theoretical_risk *= 100.0

    # Calculate R for each trade
    r_multiples = (df.loc[theoretical_risk.index, "pnl"] / theoretical_risk).values
    num_trades = len(r_multiples)

    rng = np.random.default_rng(seed=42)

    print(f"Loaded {num_trades} valid trades.")
    print(f"Avg R-Multiple: {np.mean(r_multiples):.2f}R")
    print(f"Running {a.sims:,} logic-aware simulations...")

    final_balances = []
    max_drawdowns = []
    max_streaks = []
    bust_count = 0

    for i in range(a.sims):
        final_bal, max_dd, streak = run_simulation(r_multiples, num_trades, a.balance, rng)
        if final_bal is None:
            bust_count += 1
        else:
            final_balances.append(final_bal)
            max_drawdowns.append(max_dd * 100)
            max_streaks.append(streak)
        print(f"  Simulation {i+1:>5,}/{a.sims:,}", end="\r")

    print("\n\n--- Monte Carlo Simulation Results ---")

    if not final_balances:
        print("\nAll simulations resulted in ruin. System is not viable.")
        return

    prob_of_ruin = bust_count / a.sims

    print(f"\nBased on {a.sims:,} simulations:")
    print(f"  • Probability of Ruin:   {prob_of_ruin:.2%}")
    print(f"  • Median Final Balance:  ${np.median(final_balances):,.2f}")
    print(f"  • Avg Final Balance:     ${np.mean(final_balances):,.2f}")
    print("\nDistribution of Final Balances:")
    print(f"  • 5th Percentile:        ${np.percentile(final_balances, 5):,.2f} (Worst Case)")
    print(f"  • 95th Percentile:       ${np.percentile(final_balances, 95):,.2f} (Best Case)")
    print("\nDistribution of Max Drawdown:")
    print(f"  • Median Max Drawdown:   {np.median(max_drawdowns):.1f}%")
    print(f"  • 95th Percentile DD:    {np.percentile(max_drawdowns, 95):.1f}% (Worst-case DD)")
    print("\nStress Metrics:")
    print(f"  • Avg Max Losing Streak: {np.mean(max_streaks):.1f} trades")
    print(f"  • 99% Worst Streak:      {np.percentile(max_streaks, 99):.0f} trades")
    print("-" * 38)


if __name__ == "__main__":
    main()